package com.apiweather.app;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.MessageSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.support.ReloadableResourceBundleMessageSource;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;
import org.springframework.validation.beanvalidation.LocalValidatorFactoryBean;
import org.springframework.web.client.RestTemplate;

import com.apiweather.app.biz.model.weather.AgroWeather;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;


/**
 * @author a.bouabidi
 *
 */
@SpringBootApplication
@EnableAutoConfiguration
@ComponentScan(basePackages = {"com.apiweather.app"})
@EnableMongoRepositories("com.apiweather.app.biz.repo")
public class ApiweatherCoreApplication {

	public static void main(String[] args) {
		String s="[\n"
				+ "    {\n"
				+ "        \"dt\": 1626458400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 501,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"moderate rain\",\n"
				+ "                \"icon\": \"10d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.5,\n"
				+ "            \"feels_like\": 292.97,\n"
				+ "            \"temp_min\": 292.5,\n"
				+ "            \"temp_max\": 292.77,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 995,\n"
				+ "            \"humidity\": 95,\n"
				+ "            \"temp_kf\": -0.27\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.05,\n"
				+ "            \"deg\": 96,\n"
				+ "            \"gust\": 5.68\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 6.28\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 90\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626469200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 501,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"moderate rain\",\n"
				+ "                \"icon\": \"10d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.57,\n"
				+ "            \"feels_like\": 293.07,\n"
				+ "            \"temp_min\": 292.57,\n"
				+ "            \"temp_max\": 292.7,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 96,\n"
				+ "            \"temp_kf\": -0.13\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.7,\n"
				+ "            \"deg\": 83,\n"
				+ "            \"gust\": 5.81\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 11.2\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 93\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626480000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 500,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"light rain\",\n"
				+ "                \"icon\": \"10d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.55,\n"
				+ "            \"feels_like\": 293.08,\n"
				+ "            \"temp_min\": 292.55,\n"
				+ "            \"temp_max\": 292.57,\n"
				+ "            \"pressure\": 1016,\n"
				+ "            \"sea_level\": 1016,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 97,\n"
				+ "            \"temp_kf\": -0.02\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.26,\n"
				+ "            \"deg\": 83,\n"
				+ "            \"gust\": 7.27\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 2.95\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 97\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626490800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 501,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"moderate rain\",\n"
				+ "                \"icon\": \"10n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.69,\n"
				+ "            \"feels_like\": 293.26,\n"
				+ "            \"temp_min\": 292.69,\n"
				+ "            \"temp_max\": 292.69,\n"
				+ "            \"pressure\": 1015,\n"
				+ "            \"sea_level\": 1015,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 98,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 4.18,\n"
				+ "            \"deg\": 104,\n"
				+ "            \"gust\": 8.95\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 3.51\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 100\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626501600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 501,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"moderate rain\",\n"
				+ "                \"icon\": \"10n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.55,\n"
				+ "            \"feels_like\": 293.13,\n"
				+ "            \"temp_min\": 292.55,\n"
				+ "            \"temp_max\": 292.55,\n"
				+ "            \"pressure\": 1015,\n"
				+ "            \"sea_level\": 1015,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 99,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.48,\n"
				+ "            \"deg\": 72,\n"
				+ "            \"gust\": 2.9\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 3.83\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 100\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626512400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 500,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"light rain\",\n"
				+ "                \"icon\": \"10n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.12,\n"
				+ "            \"feels_like\": 292.63,\n"
				+ "            \"temp_min\": 292.12,\n"
				+ "            \"temp_max\": 292.12,\n"
				+ "            \"pressure\": 1015,\n"
				+ "            \"sea_level\": 1015,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 98,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.83,\n"
				+ "            \"deg\": 52,\n"
				+ "            \"gust\": 7.45\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 0.76\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 100\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626523200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 804,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"overcast clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.19,\n"
				+ "            \"feels_like\": 292.63,\n"
				+ "            \"temp_min\": 292.19,\n"
				+ "            \"temp_max\": 292.19,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 996,\n"
				+ "            \"humidity\": 95,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.87,\n"
				+ "            \"deg\": 36,\n"
				+ "            \"gust\": 5.6\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 100\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626534000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 804,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"overcast clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 293.77,\n"
				+ "            \"feels_like\": 294.11,\n"
				+ "            \"temp_min\": 293.77,\n"
				+ "            \"temp_max\": 293.77,\n"
				+ "            \"pressure\": 1018,\n"
				+ "            \"sea_level\": 1018,\n"
				+ "            \"grnd_level\": 997,\n"
				+ "            \"humidity\": 85,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.71,\n"
				+ "            \"deg\": 52,\n"
				+ "            \"gust\": 4.97\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 100\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626544800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 804,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"overcast clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 296.48,\n"
				+ "            \"feels_like\": 296.7,\n"
				+ "            \"temp_min\": 296.48,\n"
				+ "            \"temp_max\": 296.48,\n"
				+ "            \"pressure\": 1019,\n"
				+ "            \"sea_level\": 1019,\n"
				+ "            \"grnd_level\": 998,\n"
				+ "            \"humidity\": 70,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.61,\n"
				+ "            \"deg\": 75,\n"
				+ "            \"gust\": 4.02\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 100\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626555600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 803,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"broken clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 297.1,\n"
				+ "            \"feels_like\": 297.25,\n"
				+ "            \"temp_min\": 297.1,\n"
				+ "            \"temp_max\": 297.1,\n"
				+ "            \"pressure\": 1020,\n"
				+ "            \"sea_level\": 1020,\n"
				+ "            \"grnd_level\": 998,\n"
				+ "            \"humidity\": 65,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.81,\n"
				+ "            \"deg\": 78,\n"
				+ "            \"gust\": 4.51\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 82\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626566400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 803,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"broken clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 295.62,\n"
				+ "            \"feels_like\": 295.85,\n"
				+ "            \"temp_min\": 295.62,\n"
				+ "            \"temp_max\": 295.62,\n"
				+ "            \"pressure\": 1020,\n"
				+ "            \"sea_level\": 1020,\n"
				+ "            \"grnd_level\": 999,\n"
				+ "            \"humidity\": 74,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.88,\n"
				+ "            \"deg\": 92,\n"
				+ "            \"gust\": 5.32\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 62\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626577200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.42,\n"
				+ "            \"feels_like\": 292.65,\n"
				+ "            \"temp_min\": 292.42,\n"
				+ "            \"temp_max\": 292.42,\n"
				+ "            \"pressure\": 1021,\n"
				+ "            \"sea_level\": 1021,\n"
				+ "            \"grnd_level\": 1000,\n"
				+ "            \"humidity\": 86,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.84,\n"
				+ "            \"deg\": 101,\n"
				+ "            \"gust\": 4.52\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 2\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626588000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 291.26,\n"
				+ "            \"feels_like\": 291.42,\n"
				+ "            \"temp_min\": 291.26,\n"
				+ "            \"temp_max\": 291.26,\n"
				+ "            \"pressure\": 1022,\n"
				+ "            \"sea_level\": 1022,\n"
				+ "            \"grnd_level\": 1000,\n"
				+ "            \"humidity\": 88,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.62,\n"
				+ "            \"deg\": 79,\n"
				+ "            \"gust\": 2.96\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 1\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626598800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 290.56,\n"
				+ "            \"feels_like\": 290.71,\n"
				+ "            \"temp_min\": 290.56,\n"
				+ "            \"temp_max\": 290.56,\n"
				+ "            \"pressure\": 1022,\n"
				+ "            \"sea_level\": 1022,\n"
				+ "            \"grnd_level\": 1000,\n"
				+ "            \"humidity\": 90,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.35,\n"
				+ "            \"deg\": 32,\n"
				+ "            \"gust\": 1.49\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626609600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.31,\n"
				+ "            \"feels_like\": 292.42,\n"
				+ "            \"temp_min\": 292.31,\n"
				+ "            \"temp_max\": 292.31,\n"
				+ "            \"pressure\": 1023,\n"
				+ "            \"sea_level\": 1023,\n"
				+ "            \"grnd_level\": 1002,\n"
				+ "            \"humidity\": 82,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.92,\n"
				+ "            \"deg\": 34,\n"
				+ "            \"gust\": 3.5\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 1\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626620400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 296.97,\n"
				+ "            \"feels_like\": 296.92,\n"
				+ "            \"temp_min\": 296.97,\n"
				+ "            \"temp_max\": 296.97,\n"
				+ "            \"pressure\": 1023,\n"
				+ "            \"sea_level\": 1023,\n"
				+ "            \"grnd_level\": 1002,\n"
				+ "            \"humidity\": 58,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.75,\n"
				+ "            \"deg\": 47,\n"
				+ "            \"gust\": 4.09\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626631200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 300.3,\n"
				+ "            \"feels_like\": 300.58,\n"
				+ "            \"temp_min\": 300.3,\n"
				+ "            \"temp_max\": 300.3,\n"
				+ "            \"pressure\": 1022,\n"
				+ "            \"sea_level\": 1022,\n"
				+ "            \"grnd_level\": 1001,\n"
				+ "            \"humidity\": 48,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.8,\n"
				+ "            \"deg\": 71,\n"
				+ "            \"gust\": 3.83\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626642000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 300.93,\n"
				+ "            \"feels_like\": 301.12,\n"
				+ "            \"temp_min\": 300.93,\n"
				+ "            \"temp_max\": 300.93,\n"
				+ "            \"pressure\": 1021,\n"
				+ "            \"sea_level\": 1021,\n"
				+ "            \"grnd_level\": 1000,\n"
				+ "            \"humidity\": 47,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.49,\n"
				+ "            \"deg\": 67,\n"
				+ "            \"gust\": 4.25\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626652800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 297.73,\n"
				+ "            \"feels_like\": 297.91,\n"
				+ "            \"temp_min\": 297.73,\n"
				+ "            \"temp_max\": 297.73,\n"
				+ "            \"pressure\": 1021,\n"
				+ "            \"sea_level\": 1021,\n"
				+ "            \"grnd_level\": 1000,\n"
				+ "            \"humidity\": 64,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.56,\n"
				+ "            \"deg\": 74,\n"
				+ "            \"gust\": 4.64\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626663600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 294.48,\n"
				+ "            \"feels_like\": 294.57,\n"
				+ "            \"temp_min\": 294.48,\n"
				+ "            \"temp_max\": 294.48,\n"
				+ "            \"pressure\": 1021,\n"
				+ "            \"sea_level\": 1021,\n"
				+ "            \"grnd_level\": 1000,\n"
				+ "            \"humidity\": 73,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.06,\n"
				+ "            \"deg\": 31,\n"
				+ "            \"gust\": 1.17\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626674400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 293.46,\n"
				+ "            \"feels_like\": 293.61,\n"
				+ "            \"temp_min\": 293.46,\n"
				+ "            \"temp_max\": 293.46,\n"
				+ "            \"pressure\": 1020,\n"
				+ "            \"sea_level\": 1020,\n"
				+ "            \"grnd_level\": 999,\n"
				+ "            \"humidity\": 79,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.48,\n"
				+ "            \"deg\": 353,\n"
				+ "            \"gust\": 1.73\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626685200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 292.62,\n"
				+ "            \"feels_like\": 292.79,\n"
				+ "            \"temp_min\": 292.62,\n"
				+ "            \"temp_max\": 292.62,\n"
				+ "            \"pressure\": 1020,\n"
				+ "            \"sea_level\": 1020,\n"
				+ "            \"grnd_level\": 999,\n"
				+ "            \"humidity\": 83,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.48,\n"
				+ "            \"deg\": 0,\n"
				+ "            \"gust\": 1.92\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626696000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 294.28,\n"
				+ "            \"feels_like\": 294.41,\n"
				+ "            \"temp_min\": 294.28,\n"
				+ "            \"temp_max\": 294.28,\n"
				+ "            \"pressure\": 1021,\n"
				+ "            \"sea_level\": 1021,\n"
				+ "            \"grnd_level\": 999,\n"
				+ "            \"humidity\": 75,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.9,\n"
				+ "            \"deg\": 325,\n"
				+ "            \"gust\": 4.57\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626706800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 299.71,\n"
				+ "            \"feels_like\": 299.71,\n"
				+ "            \"temp_min\": 299.71,\n"
				+ "            \"temp_max\": 299.71,\n"
				+ "            \"pressure\": 1020,\n"
				+ "            \"sea_level\": 1020,\n"
				+ "            \"grnd_level\": 999,\n"
				+ "            \"humidity\": 53,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.7,\n"
				+ "            \"deg\": 348,\n"
				+ "            \"gust\": 4.04\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 3\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626717600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 302.67,\n"
				+ "            \"feels_like\": 302.86,\n"
				+ "            \"temp_min\": 302.67,\n"
				+ "            \"temp_max\": 302.67,\n"
				+ "            \"pressure\": 1019,\n"
				+ "            \"sea_level\": 1019,\n"
				+ "            \"grnd_level\": 998,\n"
				+ "            \"humidity\": 45,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.11,\n"
				+ "            \"deg\": 38,\n"
				+ "            \"gust\": 4.22\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 1\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626728400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 801,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"few clouds\",\n"
				+ "                \"icon\": \"02d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 302.14,\n"
				+ "            \"feels_like\": 302.56,\n"
				+ "            \"temp_min\": 302.14,\n"
				+ "            \"temp_max\": 302.14,\n"
				+ "            \"pressure\": 1018,\n"
				+ "            \"sea_level\": 1018,\n"
				+ "            \"grnd_level\": 997,\n"
				+ "            \"humidity\": 48,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.15,\n"
				+ "            \"deg\": 43,\n"
				+ "            \"gust\": 3.13\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 20\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626739200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 500,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"light rain\",\n"
				+ "                \"icon\": \"10d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 299.08,\n"
				+ "            \"feels_like\": 299.48,\n"
				+ "            \"temp_min\": 299.08,\n"
				+ "            \"temp_max\": 299.08,\n"
				+ "            \"pressure\": 1018,\n"
				+ "            \"sea_level\": 1018,\n"
				+ "            \"grnd_level\": 997,\n"
				+ "            \"humidity\": 67,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.02,\n"
				+ "            \"deg\": 284,\n"
				+ "            \"gust\": 2.87\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 0.57\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 33\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626750000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 801,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"few clouds\",\n"
				+ "                \"icon\": \"02n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 296.63,\n"
				+ "            \"feels_like\": 296.89,\n"
				+ "            \"temp_min\": 296.63,\n"
				+ "            \"temp_max\": 296.63,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 996,\n"
				+ "            \"humidity\": 71,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 1.92,\n"
				+ "            \"deg\": 294,\n"
				+ "            \"gust\": 3.79\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 11\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626760800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 294.83,\n"
				+ "            \"feels_like\": 294.99,\n"
				+ "            \"temp_min\": 294.83,\n"
				+ "            \"temp_max\": 294.83,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 996,\n"
				+ "            \"humidity\": 74,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.11,\n"
				+ "            \"deg\": 312,\n"
				+ "            \"gust\": 4.39\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 6\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626771600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 293.23,\n"
				+ "            \"feels_like\": 293.17,\n"
				+ "            \"temp_min\": 293.23,\n"
				+ "            \"temp_max\": 293.23,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 996,\n"
				+ "            \"humidity\": 72,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.63,\n"
				+ "            \"deg\": 286,\n"
				+ "            \"gust\": 6.36\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626782400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 293.63,\n"
				+ "            \"feels_like\": 293.46,\n"
				+ "            \"temp_min\": 293.63,\n"
				+ "            \"temp_max\": 293.63,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 996,\n"
				+ "            \"humidity\": 66,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 2.9,\n"
				+ "            \"deg\": 294,\n"
				+ "            \"gust\": 7.22\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 0\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626793200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 299.35,\n"
				+ "            \"feels_like\": 299.35,\n"
				+ "            \"temp_min\": 299.35,\n"
				+ "            \"temp_max\": 299.35,\n"
				+ "            \"pressure\": 1016,\n"
				+ "            \"sea_level\": 1016,\n"
				+ "            \"grnd_level\": 996,\n"
				+ "            \"humidity\": 50,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.78,\n"
				+ "            \"deg\": 272,\n"
				+ "            \"gust\": 5.62\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 2\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626804000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 800,\n"
				+ "                \"main\": \"Clear\",\n"
				+ "                \"description\": \"clear sky\",\n"
				+ "                \"icon\": \"01d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 302.8,\n"
				+ "            \"feels_like\": 303.15,\n"
				+ "            \"temp_min\": 302.8,\n"
				+ "            \"temp_max\": 302.8,\n"
				+ "            \"pressure\": 1014,\n"
				+ "            \"sea_level\": 1014,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 46,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 4.59,\n"
				+ "            \"deg\": 267,\n"
				+ "            \"gust\": 5.9\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 6\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626814800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 500,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"light rain\",\n"
				+ "                \"icon\": \"10d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 303.39,\n"
				+ "            \"feels_like\": 304.4,\n"
				+ "            \"temp_min\": 303.39,\n"
				+ "            \"temp_max\": 303.39,\n"
				+ "            \"pressure\": 1013,\n"
				+ "            \"sea_level\": 1013,\n"
				+ "            \"grnd_level\": 992,\n"
				+ "            \"humidity\": 49,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 5.7,\n"
				+ "            \"deg\": 276,\n"
				+ "            \"gust\": 7.62\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 0.21\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 35\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626825600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 500,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"light rain\",\n"
				+ "                \"icon\": \"10d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 298.18,\n"
				+ "            \"feels_like\": 298.64,\n"
				+ "            \"temp_min\": 298.18,\n"
				+ "            \"temp_max\": 298.18,\n"
				+ "            \"pressure\": 1013,\n"
				+ "            \"sea_level\": 1013,\n"
				+ "            \"grnd_level\": 993,\n"
				+ "            \"humidity\": 73,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 4.94,\n"
				+ "            \"deg\": 304,\n"
				+ "            \"gust\": 9.33\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 1.26\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 37\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626836400,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 500,\n"
				+ "                \"main\": \"Rain\",\n"
				+ "                \"description\": \"light rain\",\n"
				+ "                \"icon\": \"10n\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 293.24,\n"
				+ "            \"feels_like\": 293.6,\n"
				+ "            \"temp_min\": 293.24,\n"
				+ "            \"temp_max\": 293.24,\n"
				+ "            \"pressure\": 1015,\n"
				+ "            \"sea_level\": 1015,\n"
				+ "            \"grnd_level\": 994,\n"
				+ "            \"humidity\": 88,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 4.07,\n"
				+ "            \"deg\": 13,\n"
				+ "            \"gust\": 7.96\n"
				+ "        },\n"
				+ "        \"rain\": {\n"
				+ "            \"3h\": 1.24\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 69\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626847200,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 803,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"broken clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 291.23,\n"
				+ "            \"feels_like\": 291.26,\n"
				+ "            \"temp_min\": 291.23,\n"
				+ "            \"temp_max\": 291.23,\n"
				+ "            \"pressure\": 1016,\n"
				+ "            \"sea_level\": 1016,\n"
				+ "            \"grnd_level\": 995,\n"
				+ "            \"humidity\": 83,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.63,\n"
				+ "            \"deg\": 10,\n"
				+ "            \"gust\": 8.74\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 83\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626858000,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 803,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"broken clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 290.09,\n"
				+ "            \"feels_like\": 290.06,\n"
				+ "            \"temp_min\": 290.09,\n"
				+ "            \"temp_max\": 290.09,\n"
				+ "            \"pressure\": 1017,\n"
				+ "            \"sea_level\": 1017,\n"
				+ "            \"grnd_level\": 995,\n"
				+ "            \"humidity\": 85,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.19,\n"
				+ "            \"deg\": 1,\n"
				+ "            \"gust\": 7.84\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 69\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626868800,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 803,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"broken clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 290.82,\n"
				+ "            \"feels_like\": 290.65,\n"
				+ "            \"temp_min\": 290.82,\n"
				+ "            \"temp_max\": 290.82,\n"
				+ "            \"pressure\": 1019,\n"
				+ "            \"sea_level\": 1019,\n"
				+ "            \"grnd_level\": 997,\n"
				+ "            \"humidity\": 77,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.55,\n"
				+ "            \"deg\": 8,\n"
				+ "            \"gust\": 8.18\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 80\n"
				+ "        }\n"
				+ "    },\n"
				+ "    {\n"
				+ "        \"dt\": 1626879600,\n"
				+ "        \"weather\": [\n"
				+ "            {\n"
				+ "                \"id\": 804,\n"
				+ "                \"main\": \"Clouds\",\n"
				+ "                \"description\": \"overcast clouds\",\n"
				+ "                \"icon\": \"04d\"\n"
				+ "            }\n"
				+ "        ],\n"
				+ "        \"main\": {\n"
				+ "            \"temp\": 295.31,\n"
				+ "            \"feels_like\": 294.89,\n"
				+ "            \"temp_min\": 295.31,\n"
				+ "            \"temp_max\": 295.31,\n"
				+ "            \"pressure\": 1019,\n"
				+ "            \"sea_level\": 1019,\n"
				+ "            \"grnd_level\": 998,\n"
				+ "            \"humidity\": 50,\n"
				+ "            \"temp_kf\": 0\n"
				+ "        },\n"
				+ "        \"wind\": {\n"
				+ "            \"speed\": 3.79,\n"
				+ "            \"deg\": 23,\n"
				+ "            \"gust\": 5.3\n"
				+ "        },\n"
				+ "        \"clouds\": {\n"
				+ "            \"all\": 92\n"
				+ "        }\n"
				+ "    }\n"
				+ "]";
		ObjectMapper map = new ObjectMapper ();
		AgroWeather[] liste = null;
		try {
			liste = map.readValue(s, AgroWeather[].class);
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		SpringApplication.run(ApiweatherCoreApplication.class, args);
	}

	@Bean
	public MessageSource messageSource() {
		ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
		messageSource.setBasename("classpath:messages");
		messageSource.setDefaultEncoding("UTF-8");
		return messageSource;
	}

	@Bean
	public LocalValidatorFactoryBean getValidator() {
		LocalValidatorFactoryBean bean = new LocalValidatorFactoryBean();
		bean.setValidationMessageSource(messageSource());
		return bean;
	}

	@Bean
	public OpenAPI customOpenAPI(@Value("${application-description}") String appDesciption,
			@Value("${application-version}") String appVersion) {
		return new OpenAPI().info(new Info().title("sample application API").version(appVersion)
				.description(appDesciption).termsOfService("http://swagger.io/terms/")
				.license(new License().name("Apache 2.0").url("http://springdoc.org")));
	}

	

}
